name: build and test

on: 
  push:
  schedule:
    - cron: '* 10 * * *'

jobs:
  job_build_and_test:
    name: build_docker_image
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: ls ${{ github.workspace }}
      - name: Build docker-compose
        run: docker-compose build
      - name: Launch docker-compose
        run: docker-compose up -d
      - name: Test connection
        run: |
          sleep 60
          ./test/test.bash
  job_make_suc_badge:
    name: Make test success badge
    runs-on: ubuntu-latest
    needs: job_build_and_test
    steps:
      - id: suc_date
        run: echo "##[set-output name=data;]$(date -Iseconds)"
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: suc_time
          LABEL: 'テスト成功 at'
          STATUS: ${{ steps.suc_date.outputs.data }}
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  job_testdate_badge:
    runs-on: ubuntu-latest
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date -Iseconds)"
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: time
          LABEL: 'テスト実施 at'
          STATUS: ${{ steps.date.outputs.data }}
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
